# languages.py - Dil tanımlamaları ve yönetim fonksiyonları
import os # Yükleme mesajlarında kullanmak için eklendi

# Varsayılan dil
current_lang = "English"

# Tüm metinleri içeren sözlük
# Not: Lütfen buradaki anahtarların main.py'deki get_text() çağrıları ile eşleştiğinden emin olun.
languages = {
    "English": {
        "title": "WAMP Auto Fixer",
        "scan": "Start Scan",
        "auto_fix": "Auto-Fix",
        "dark_mode": "Dark Mode",
        "exit": "Exit",
        "options": "Options",
        "language": "Language",
        "port_check": "--- Port Check ---",
        "apache_check": "--- Apache Service Check ---",
        "admin_warning": "Please run the program as administrator!",
        "only_windows": "This tool only runs on Windows.",
        "scan_started": "=== System Scan Started ===",
        "scan_completed": "=== Scan Completed ===",
        "auto_fix_started": "=== Auto-Fix Started ===",
        "auto_fix_completed": "=== Auto-Fix Completed ===",
        "vc_missing_found": "Missing Visual C++ packages found:",
        "vc_all_installed": "All Visual C++ packages are installed.",
        "vc_installing": "[VC++] Installing {package}...",
        "vc_installed_success": "[VC++] {package} installed successfully.",
        "vc_installed_fail": "[VC++] {package} installation failed: {msg}",
        "port_status": "Port {port} is free.",
        "port_used": "Port {port} is being used by {name} (PID: {pid})",
        "apache_running": "WAMP Apache service is running.",
        "apache_stopped": "WAMP Apache service is stopped. You can start it with Auto-Fix.",
        "apache_status": "Apache service status: {status}",
        "apache_starting": "[APACHE] Starting...",
        "apache_started": "[APACHE] Started.",
        "apache_already": "[APACHE] Already running.",
        "downloading_file": "[DOWNLOADING] {file}",
        "download_failed": "[ERROR] Could not download {file}: {msg}",
        "unknown_process": "Unknown Process",
        
        # YENİ GENEL ONAY METİNLERİ
        "general_fix_confirm_title": "⚠️ System Change Confirmation",
        "general_fix_confirm_text": "The Auto-Fix process will make changes to your system, such as installing VC++ and starting/stopping the Apache service. Do you want to continue? (You proceed at your own risk!)",
        "fix_cancelled": "Process cancelled due to lack of user confirmation.",
    },

    "Türkçe": {
        "title": "WAMP Auto Fixer",
        "scan": "Tarama Başlat",
        "auto_fix": "Otomatik Düzelt",
        "dark_mode": "Karanlık Mod",
        "exit": "Çıkış",
        "options": "Seçenekler",
        "language": "Dil",
        "port_check": "--- Port Kontrolü ---",
        "apache_check": "--- Apache Servis Kontrolü ---",
        "admin_warning": "Programı yönetici olarak çalıştırın!",
        "only_windows": "Bu araç sadece Windows'ta çalışır.",
        "scan_started": "=== Sistem Taraması Başladı ===",
        "scan_completed": "=== Tarama Tamamlandı ===",
        "auto_fix_started": "=== Auto-Fix Başlatıldı ===",
        "auto_fix_completed": "=== Auto-Fix Tamamlandı ===",
        "vc_missing_found": "Eksik Visual C++ paketleri bulundu:",
        "vc_all_installed": "Tüm Visual C++ paketleri kurulu.",
        "vc_installing": "[VC++] {package} kuruluyor...",
        "vc_installed_success": "[VC++] {package} başarıyla kuruldu.",
        "vc_installed_fail": "[VC++] {package} kurulamadı: {msg}",
        "port_status": "Port {port} boş.",
        "port_used": "Port {port} şu program tarafından kullanılıyor: {name} (PID: {pid})",
        "apache_running": "WAMP Apache servisi çalışıyor.",
        "apache_stopped": "WAMP Apache servisi durdurulmuş. Auto-Fix ile başlatabilirsiniz.",
        "apache_status": "Apache servis durumu: {status}",
        "apache_starting": "[APACHE] Başlatılıyor...",
        "apache_started": "[APACHE] Başlatıldı.",
        "apache_already": "[APACHE] Zaten çalışıyor.",
        "downloading_file": "[İNDİRİLİYOR] {file}",
        "download_failed": "[HATA] Dosya indirilemedi: {file}: {msg}",
        "unknown_process": "Bilinmeyen",
        
        # YENİ GENEL ONAY METİNLERİ
        "general_fix_confirm_title": "⚠️ Sistem Değişikliği Onayı",
        "general_fix_confirm_text": "Otomatik düzeltme işlemi, VC++ kurulumu ve Apache hizmetini başlatma/durdurma gibi sisteminizde değişiklikler yapacaktır. Devam etmek istiyor musunuz? (Sorumluluk size aittir!)",
        "fix_cancelled": "İşlem, kullanıcı onayı olmadan iptal edildi.",
    },

    "Español": {
        "title": "WAMP Auto Fixer",
        "scan": "Iniciar Escaneo",
        "auto_fix": "Auto-Corregir",
        "dark_mode": "Modo Oscuro",
        "exit": "Salir",
        "options": "Opciones",
        "language": "Idioma",
        "port_check": "--- Comprobación de Puertos ---",
        "apache_check": "--- Comprobación del Servicio Apache ---",
        "admin_warning": "¡Ejecute el programa como administrador!",
        "only_windows": "Esta herramienta solo funciona en Windows.",
        "scan_started": "=== Escaneo del Sistema Iniciado ===",
        "scan_completed": "=== Escaneo Completado ===",
        "auto_fix_started": "=== Auto-Corregir Iniciado ===",
        "auto_fix_completed": "=== Auto-Corregir Completado ===",
        "vc_missing_found": "Se encontraron paquetes de Visual C++ faltantes:",
        "vc_all_installed": "Todos los paquetes de Visual C++ están instalados.",
        "vc_installing": "[VC++] Instalando {package}...",
        "vc_installed_success": "[VC++] {package} instalado correctamente.",
        "vc_installed_fail": "[VC++] {package} no se pudo instalar: {msg}",
        "port_status": "Puerto {port} libre.",
        "port_used": "Puerto {port} está siendo usado por {name} (PID: {pid})",
        "apache_running": "Servicio WAMP Apache en ejecución.",
        "apache_stopped": "Servicio WAMP Apache detenido. Puede iniciarlo con Auto-Fix.",
        "apache_status": "Estado del servicio Apache: {status}",
        "apache_starting": "[APACHE] Iniciando...",
        "apache_started": "[APACHE] Iniciado.",
        "apache_already": "[APACHE] Ya en ejecución.",
        "downloading_file": "[DESCARGANDO] {file}",
        "download_failed": "[ERROR] No se pudo descargar {file}: {msg}",
        "unknown_process": "Proceso Desconocido",
        
        # YENİ GENEL ONAY METİNLERİ
        "general_fix_confirm_title": "⚠️ Confirmación de Cambio del Sistema",
        "general_fix_confirm_text": "El proceso de Auto-Corregir realizará cambios en su sistema, como la instalación de VC++ y el inicio/parada del servicio Apache. ¿Desea continuar? (¡Usted procede bajo su propio riesgo!)",
        "fix_cancelled": "Proceso cancelado debido a la falta de confirmación del usuario.",
    },

    "Français": {
        "title": "WAMP Auto Fixer",
        "scan": "Lancer l'analyse",
        "auto_fix": "Réparation automatique",
        "dark_mode": "Mode Sombre",
        "exit": "Quitter",
        "options": "Options",
        "language": "Langue",
        "port_check": "--- Vérification des Ports ---",
        "apache_check": "--- Vérification du Service Apache ---",
        "admin_warning": "Veuillez exécuter le programme en tant qu'administrateur !",
        "only_windows": "Cet outil fonctionne uniquement sous Windows.",
        "scan_started": "=== Analyse du système démarrée ===",
        "scan_completed": "=== Analyse terminée ===",
        "auto_fix_started": "=== Réparation automatique démarrée ===",
        "auto_fix_completed": "=== Réparation automatique terminée ===",
        "vc_missing_found": "Packs Visual C++ manquants trouvés :",
        "vc_all_installed": "Tous les packs Visual C++ sont installés.",
        "vc_installing": "[VC++] Installation de {package}...",
        "vc_installed_success": "[VC++] {package} installé avec succès.",
        "vc_installed_fail": "[VC++] Échec de l'installation de {package} : {msg}",
        "port_status": "Le port {port} est libre.",
        "port_used": "Le port {port} est utilisé par {name} (PID : {pid})",
        "apache_running": "Le service Apache WAMP est en cours d'exécution.",
        "apache_stopped": "Le service Apache WAMP est arrêté. Vous pouvez le démarrer avec Auto-Fix.",
        "apache_status": "État du service Apache : {status}",
        "apache_starting": "[APACHE] Démarrage...",
        "apache_started": "[APACHE] Démarré.",
        "apache_already": "[APACHE] Déjà en cours.",
        "downloading_file": "[TÉLÉCHARGEMENT] {file}",
        "download_failed": "[ERREUR] Impossible de télécharger {file} : {msg}",
        "unknown_process": "Processus Inconnu",
        
        # YENİ GENEL ONAY METİNLERİ
        "general_fix_confirm_title": "⚠️ Confirmation de Modification du Système",
        "general_fix_confirm_text": "Le processus de Réparation automatique apportera des modifications à votre système, telles que l'installation de VC++ et le démarrage/l'arrêt du service Apache. Voulez-vous continuer ? (Vous procédez à vos propres risques !)",
        "fix_cancelled": "Processus annulé en l'absence de confirmation de l'utilisateur.",
    },

    "Deutsch": {
        "title": "WAMP Auto Fixer",
        "scan": "Scan starten",
        "auto_fix": "Auto-Reparatur",
        "dark_mode": "Dunkelmodus",
        "exit": "Beenden",
        "options": "Optionen",
        "language": "Sprache",
        "port_check": "--- Portprüfung ---",
        "apache_check": "--- Apache-Dienstprüfung ---",
        "admin_warning": "Bitte das Programm als Administrator ausführen!",
        "only_windows": "Dieses Tool läuft nur unter Windows.",
        "scan_started": "=== Systemscan gestartet ===",
        "scan_completed": "=== Scan abgeschlossen ===",
        "auto_fix_started": "=== Auto-Reparatur gestartet ===",
        "auto_fix_completed": "=== Auto-Reparatur abgeschlossen ===",
        "vc_missing_found": "Fehlende Visual C++ Pakete gefunden:",
        "vc_all_installed": "Alle Visual C++ Pakete sind installiert.",
        "vc_installing": "[VC++] Installiere {package}...",
        "vc_installed_success": "[VC++] {package} erfolgreich installiert.",
        "vc_installed_fail": "[VC++] Fehler bei der Installation von {package}: {msg}",
        "port_status": "Port {port} ist frei.",
        "port_used": "Port {port} wird verwendet von {name} (PID: {pid})",
        "apache_running": "WAMP Apache Dienst läuft.",
        "apache_stopped": "WAMP Apache Dienst ist gestoppt. Auto-Fix kann ihn starten.",
        "apache_status": "Apache Dienststatus: {status}",
        "apache_starting": "[APACHE] Starte...",
        "apache_started": "[APACHE] Gestartet.",
        "apache_already": "[APACHE] Läuft bereits.",
        "downloading_file": "[HERUNTERLADEN] {file}",
        "download_failed": "[FEHLER] Datei konnte nicht geladen werden: {file}: {msg}",
        "unknown_process": "Unbekannter Prozess",
        
        # YENİ GENEL ONAY METİNLERİ
        "general_fix_confirm_title": "⚠️ Bestätigung der Systemänderung",
        "general_fix_confirm_text": "Der Auto-Reparaturprozess nimmt Änderungen an Ihrem System vor, wie die Installation von VC++ und das Starten/Stoppen des Apache-Dienstes. Möchten Sie fortfahren? (Sie handeln auf eigenes Risiko!)",
        "fix_cancelled": "Der Vorgang wurde mangels Benutzerbestätigung abgebrochen.",
    },

    "Русский": {
        "title": "WAMP Auto Fixer",
        "scan": "Начать сканирование",
        "auto_fix": "Авто-исправление",
        "dark_mode": "Тёмная тема",
        "exit": "Выход",
        "options": "Настройки",
        "language": "Язык",
        "port_check": "--- Проверка портов ---",
        "apache_check": "--- Проверка сервиса Apache ---",
        "admin_warning": "Запустите программу от имени администратора!",
        "only_windows": "Инструмент работает только в Windows.",
        "scan_started": "=== Начато сканирование системы ===",
        "scan_completed": "=== Сканирование завершено ===",
        "auto_fix_started": "=== Авто-исправление начато ===",
        "auto_fix_completed": "=== Авто-исправление завершено ===",
        "vc_missing_found": "Обнаружены отсутствующие пакеты Visual C++:",
        "vc_all_installed": "Все пакеты Visual C++ установлены.",
        "vc_installing": "[VC++] Устанавливается {package}...",
        "vc_installed_success": "[VC++] {package} успешно установлен.",
        "vc_installed_fail": "[VC++] Ошибка установки {package}: {msg}",
        "port_status": "Порт {port} свободен.",
        "port_used": "Порт {port} используется процессом {name} (PID: {pid})",
        "apache_running": "Сервис WAMP Apache запущен.",
        "apache_stopped": "Сервис WAMP Apache остановлен. Запустите через Auto-Fix.",
        "apache_status": "Статус сервиса Apache: {status}",
        "apache_starting": "[APACHE] Запуск...",
        "apache_started": "[APACHE] Запущено.",
        "apache_already": "[APACHE] Уже работает.",
        "downloading_file": "[ЗАГРУЗКА] {file}",
        "download_failed": "[ОШИБКА] Не удалось загрузить {file}: {msg}",
        "unknown_process": "Неизвестный процесс",
        
        # YENİ GENEL ONAY METİNLERİ
        "general_fix_confirm_title": "⚠️ Подтверждение изменения системы",
        "general_fix_confirm_text": "Процесс Авто-исправления внесет изменения в вашу систему, такие как установка VC++ и запуск/остановка сервиса Apache. Вы хотите продолжить? (Вы действуете на свой страх и риск!)",
        "fix_cancelled": "Процесс отменен из-за отсутствия подтверждения пользователя.",
    },

    "العربية": {
        "title": "WAMP Auto Fixer",
        "scan": "بدء الفحص",
        "auto_fix": "إصلاح تلقائي",
        "dark_mode": "الوضع الليلي",
        "exit": "خروج",
        "options": "الإعدادات",
        "language": "اللغة",
        "port_check": "--- فحص المنافذ ---",
        "apache_check": "--- فحص خدمة Apache ---",
        "admin_warning": "يرجى تشغيل البرنامج كمسؤول!",
        "only_windows": "هذه الأداة تعمل فقط على ويندوز.",
        "scan_started": "=== بدأ فحص النظام ===",
        "scan_completed": "=== اكتمل الفحص ===",
        "auto_fix_started": "=== بدأ الإصلاح التلقائي ===",
        "auto_fix_completed": "=== تم الإصلاح التلقائي ===",
        "vc_missing_found": "تم العثور على حزم Visual C++ المفقودة:",
        "vc_all_installed": "جميع حزم Visual C++ مثبتة.",
        "vc_installing": "[VC++] يتم تثبيت {package}...",
        "vc_installed_success": "[VC++] تم تثبيت {package} بنجاح.",
        "vc_installed_fail": "[VC++] فشل تثبيت {package}: {msg}",
        "port_status": "المنفذ {port} فارغ.",
        "port_used": "يتم استخدام المنفذ {port} من قبل {name} (PID: {pid})",
        "apache_running": "خدمة Apache تعمل.",
        "apache_stopped": "خدمة Apache متوقفة. يمكنك تشغيلها عبر Auto-Fix.",
        "apache_status": "حالة خدمة Apache: {status}",
        "apache_starting": "[APACHE] جارٍ التشغيل...",
        "apache_started": "[APACHE] تم التشغيل.",
        "apache_already": "[APACHE] يعمل بالفعل.",
        "downloading_file": "[جارٍ التحميل] {file}",
        "download_failed": "[خطأ] تعذر تحميل {file}: {msg}",
        "unknown_process": "عملية غير معروفة",
        
        # YENİ GENEL ONAY METİNLERİ
        "general_fix_confirm_title": "⚠️ تأكيد تغيير النظام",
        "general_fix_confirm_text": "ستقوم عملية الإصلاح التلقائي بإجراء تغييرات على نظامك، مثل تثبيت VC++ وبدء/إيقاف خدمة Apache. هل تريد المتابعة؟ (أنت تتقدم على مسؤوليتك الخاصة!)",
        "fix_cancelled": "تم إلغاء العملية لعدم تأكيد المستخدم.",
    },

    "Italiano": {
        "title": "WAMP Auto Fixer",
        "scan": "Avvia Scansione",
        "auto_fix": "Correzione Automatica",
        "dark_mode": "Modalità Scura",
        "exit": "Esci",
        "options": "Opzioni",
        "language": "Lingua",
        "port_check": "--- Controllo Porte ---",
        "apache_check": "--- Controllo Servizio Apache ---",
        "admin_warning": "Esegui il programma come amministratore!",
        "only_windows": "Questo strumento funziona solo su Windows.",
        "scan_started": "=== Scansione del sistema avviata ===",
        "scan_completed": "=== Scansione completata ===",
        "auto_fix_started": "=== Correzione Automatica avviata ===",
        "auto_fix_completed": "=== Correzione Automatica completata ===",
        "vc_missing_found": "Pacchetti Visual C++ mancanti trovati:",
        "vc_all_installed": "Tutti i pacchetti Visual C++ sono installati.",
        "vc_installing": "[VC++] Installazione di {package}...",
        "vc_installed_success": "[VC++] {package} installato con successo.",
        "vc_installed_fail": "[VC++] Installazione di {package} fallita: {msg}",
        "port_status": "La porta {port} è libera.",
        "port_used": "La porta {port} è utilizzata da {name} (PID: {pid})",
        "apache_running": "Il servizio Apache è in esecuzione.",
        "apache_stopped": "Il servizio Apache è fermo. Puoi avviarlo tramite Auto-Fix.",
        "apache_status": "Stato del servizio Apache: {status}",
        "apache_starting": "[APACHE] Avvio...",
        "apache_started": "[APACHE] Avviato.",
        "apache_already": "[APACHE] Già in esecuzione.",
        "downloading_file": "[DOWNLOAD] {file}",
        "download_failed": "[ERRORE] Impossibile scaricare {file}: {msg}",
        "unknown_process": "Processo Sconosciuto",
        
        # YENİ GENEL ONAY METİNLERİ
        "general_fix_confirm_title": "⚠️ Conferma Modifica Sistema",
        "general_fix_confirm_text": "Il processo di Correzione Automatica apporterà modifiche al tuo sistema, come l'installazione di VC++ e l'avvio/arresto del servizio Apache. Vuoi continuare? (Si procede a proprio rischio!)",
        "fix_cancelled": "Processo annullato per mancanza di conferma dell'utente.",
    },

    "日本語": {
        "title": "WAMP Auto Fixer",
        "scan": "スキャン開始",
        "auto_fix": "自動修復",
        "dark_mode": "ダークモード",
        "exit": "終了",
        "options": "オプション",
        "language": "言語",
        "port_check": "--- ポートチェック ---",
        "apache_check": "--- Apache サービスチェック ---",
        "admin_warning": "管理者として実行してください！",
        "only_windows": "このツールは Windows でのみ動作します。",
        "scan_started": "=== システムスキャン開始 ===",
        "scan_completed": "=== スキャン完了 ===",
        "auto_fix_started": "=== 自動修復開始 ===",
        "auto_fix_completed": "=== 自動修復完了 ===",
        "vc_missing_found": "不足している Visual C++ パッケージ:",
        "vc_all_installed": "すべての Visual C++ パッケージがインストールされています。",
        "vc_installing": "[VC++] {package} をインストール中...",
        "vc_installed_success": "[VC++] {package} が正常にインストールされました。",
        "vc_installed_fail": "[VC++] {package} のインストールに失敗しました: {msg}",
        "port_status": "ポート {port} は空いています。",
        "port_used": "ポート {port} は {name} によって使用されています (PID: {pid})",
        "apache_running": "WAMP Apache サービスは実行中です。",
        "apache_stopped": "WAMP Apache サービスは停止しています。Auto-Fix で開始できます。",
        "apache_status": "Apache サービスの状態: {status}",
        "apache_starting": "[APACHE] 起動中...",
        "apache_started": "[APACHE] 起動しました。",
        "apache_already": "[APACHE] すでに実行中です。",
        "downloading_file": "[ダウンロード中] {file}",
        "download_failed": "[エラー] {file} をダウンロードできませんでした: {msg}",
        "unknown_process": "不明なプロセス",
        
        # YENİ GENEL ONAY METİNLERİ
        "general_fix_confirm_title": "⚠️ システム変更の確認",
        "general_fix_confirm_text": "自動修復プロセスは、VC++のインストールやApacheサービスの開始/停止など、システムに変更を加えます。続行しますか？ (ご自身の責任で進めてください!)",
        "fix_cancelled": "ユーザーの確認がないため、プロセスがキャンセルされました。",
    },

    "中文": {
        "title": "WAMP Auto Fixer",
        "scan": "开始扫描",
        "auto_fix": "自动修复",
        "dark_mode": "深色模式",
        "exit": "退出",
        "options": "选项",
        "language": "语言",
        "port_check": "--- 端口检查 ---",
        "apache_check": "--- Apache 服务检查 ---",
        "admin_warning": "请以管理员身份运行程序！",
        "only_windows": "此工具仅在 Windows 上运行。",
        "scan_started": "=== 系统扫描已开始 ===",
        "scan_completed": "=== 扫描完成 ===",
        "auto_fix_started": "=== 自动修复已开始 ===",
        "auto_fix_completed": "=== 自动修复已完成 ===",
        "vc_missing_found": "发现缺少的 Visual C++ 包：",
        "vc_all_installed": "所有 Visual C++ 包均已安装。",
        "vc_installing": "[VC++] 正在安装 {package}...",
        "vc_installed_success": "[VC++] {package} 安装成功。",
        "vc_installed_fail": "[VC++] {package} 安装失败：{msg}",
        "port_status": "端口 {port} 空闲。",
        "port_used": "端口 {port} 正被 {name} 使用 (PID: {pid})",
        "apache_running": "WAMP Apache 服务正在运行。",
        "apache_stopped": "WAMP Apache 服务已停止。你可以使用 Auto-Fix 启动它。",
        "apache_status": "Apache 服务状态：{status}",
        "apache_starting": "[APACHE] 正在启动...",
        "apache_started": "[APACHE] 已启动。",
        "apache_already": "[APACHE] 已在运行。",
        "downloading_file": "[下载中] {file}",
        "download_failed": "[错误] 无法下载 {file}: {msg}",
        "unknown_process": "未知进程",
        
        # YENİ GENEL ONAY METİNLERİ
        "general_fix_confirm_title": "⚠️ 系统更改确认",
        "general_fix_confirm_text": "自动修复过程将对您的系统进行更改，例如安装 VC++ 和启动/停止 Apache 服务。您要继续吗？ (风险自负!)",
        "fix_cancelled": "因缺乏用户确认，流程已取消。",
    }
}

current_lang = "English"

def get_text(key):
    return languages[current_lang].get(key, key)

def set_current_lang(lang):
    global current_lang
    if lang in languages:
        current_lang = lang